report

diff --git a/.github/workflows/shell-check.yml b/.github/workflows/shell-check.yml
--- a/.github/workflows/shell-check.yml
+++ b/.github/workflows/shell-check.yml
@@ -40,7 +40,7 @@ jobs:
         token: ${{ secrets.TOKEN_ACTIONS }}
     - name: Scan for sensitive data
       run: |
-        echo "Scanning for sensitive data in shell scripts..."
+        echo "EScaneando datos sensibles en la shell..."
 
         # Define the pattern to search for
         PATTERN="PASS|PWD|PASSWORD|PSWD"
@@ -58,11 +58,13 @@ jobs:
         # Check if report contains any matches
         if [ -s $REPORT_FILE ]; then
           echo "Sensitive data found. Report generated: $REPORT_FILE"
+          exit 1  # Fail the job if sensitive data is found
         else
-          echo "No sensitive data found." >> $REPORT_FILE
+          echo "No sensitive data found."
         fi
 
     - name: Upload sensitive data report
+      if: failure()  # Only upload the report if the previous step failed
       uses: actions/upload-artifact@v3
       with:
         name: sensitive-data-report
